# Generated by Django 5.2.8 on 2026-08-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinayaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Amount', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('SenderNumber', models.CharField(max_length=20)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
